### ISSUE TITLE
Thanks for posting Tisean / Question about 'unsupported' folder

### ISSUE THREAD

**Issue by gazeek** [heggus/Tisean#1]
I didn't know how else to contact you, so I just wanted to ask:

Does the contents of 'unsupported' have anything to do with the rest of the project?

The reason I am asking this is because there are similar files in the 'unsopported' folder and in other folders (examples are 'd2.c' in 'unsupported' and in 'source_c' and 'surrogates.f' in unsupported and in 'source_f'). 

Does this mean that the 'd2.c' in 'source_c' is not an important program? or is it that merely the version of 'd2.c' in the 'unsupported' folder is no longer important, and the 'd2.c' in 'source_c' is still a good program (hasn't been deprecated, or anything like that)?

Thanks for posting the Tisean package here.

Regards,

Piotr Held

**Comment by heggus** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,
don't care about unsupported. These are typically old versions of
programs that we wanted to keep for some reason. I guess I will remove
this directory from the master branch.

Rainer


Dr. Rainer Hegger
J.W. Goethe University
Institute for Physical and Theoretical Chemistry
Max-von-Laue-Str. 7, 60438 Frankfurt/Main, Germany
Email:  hegger@theochem.uni-frankfurt.de
Tel: +49-(0)69-798-29704, Fax: +49-(0)69-798-29709

On 21.04.2015 02:15, gazeek wrote:
> I didn't know how else to contact you, so I just wanted to ask:
> 
> Does the contents of 'unsupported' have anything to do with the
> rest of the project?
> 
> The reason I am asking this is because there are similar files in
> the 'unsopported' folder and in other folders (examples are 'd2.c'
> in 'unsupported' and in 'source_c' and 'surrogates.f' in
> unsupported and in 'source_f').
> 
> Does this mean that the 'd2.c' in 'source_c' is not an important
> program? or is it that merely the version of 'd2.c' in the
> 'unsupported' folder is no longer important, and the 'd2.c' in
> 'source_c' is still a good program (hasn't been deprecated, or
> anything like that)?
> 
> Thanks for posting the Tisean package here.
> 
> Regards,
> 
> Piotr Held
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/heggus/Tisean/issues/1
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iEYEARECAAYFAlU1+QMACgkQk613F9QPbQJWegCfXGIYjKWxRxC4j/4cZxLD5txn
PiIAoJ98qmqxlIyDGwm29DI96cEe5zPj
=ZvsH
-----END PGP SIGNATURE-----

**Comment by gazeek** [comment]
Thanks for the info.

Piotr Held
