### ISSUE TITLE
Spectrum.f does not give proper step response.

### ISSUE THREAD

**Issue by gazeek** [heggus/Tisean#3]
It seems as though this program does not work properly in certain instances. If you have access to octave you can run the 'test_spectrum.m' file from folder 'tests/spectrum' located in this repo: https://bitbucket.org/josiah425/tisean 

The problem seems to appear when the 'spectrum' is calculated with default flags on a square function (in file 'square.dat' in that folder -- which is 2000 x 0 then 2000 x 1 then 2000 x 0 again, for a total of 6000 values). In this case there seems to be a "shadow" below the proper spectrum values for this function (see attached graphcs). This might be a problem with 'store_spec()' or with 'rffti1()' or with 'rfftf1()' which might be problematic also for other functions.
![bad_step_tisean](https://cloud.githubusercontent.com/assets/1235921/7575456/1c889928-f7f2-11e4-8ad2-e6488bc9d870.png)

Thanks for all of your help up till now.

**Comment by heggus** [comment]
If I did the analytical calculations correctly (not guaranteed :) ) the spectrum should be zero for every third frequency. 10^-20 is sufficiently close to zero I would say. So, I would say, the spectrum looks reasonable. Not nice but reasonable. If you use the fft routine of octave on your data, you will get the same, except that there 10^-20 is really zero.

**Comment by gazeek** [comment]
I see. That's great news ! :) 
Thanks a lot for looking at it.
