### ISSUE TITLE
delay.c

### ISSUE THREAD

**Issue by gazeek** [heggus/Tisean#6]
I have a question: 
delay.c gives two different outputs depending on whether the output is written to `stdout` or to `fout`. The problem seems to be that `rundel` in line 299 (writing to `stdout`) is out of the inmost `for` loop and it is in the innermost `for` loop when writing to `fout` (in line 314). So for input:
1 1
2 2
3 3
4 4
5 5
6 6
7 7 
8 8 
9 9 
10 10

You get 2 different results depending on whether the `-o` flag is used.
When running `delay -M2 -D1,2 -m4 -o out.dat`  the result is:
3 2 3 2
4 3 4 3
5 4 5 4
6 5 6 5
7 6 7 6
8 7 8 7
9 8 9 8
10 9 10 9

But when running `delay -M2 -D1,2 -m4`  the result is:
3 2 3 1
4 3 4 2
5 4 5 3
6 5 6 4
7 6 7 5
8 7 8 6
9 8 9 7
10 9 10 8

Which is the correct outcome?

**Comment by heggus** [comment]
The correct output was that of stdout. Commit e6a5a5426bb663906898379648de82581f9c416d fixes the problem. Thanks.
