### ISSUE TITLE
lzo-run.c: Parameter 'K'

### ISSUE THREAD

**Issue by gazeek** [heggus/Tisean#7]
Is `K` (capital K) a dead parameter?

The only thing it does is in line 109 `setsort=1;`, but the default for `setsort` is also 1. This default is set in line 38: `setsort=1`.

**Comment by heggus** [comment]
Sorry for the delay. I was out for vacation.

I will fix this issue asap. The -K should not be a dummy option. I will introduce it to lzo-test as well.

**Comment by heggus** [comment]
Fixed.
